name: Trigger DevOps Release

on:
  push:
    branches:
      - release  # Exemplo: dispara quando há um push na branch 'release'

jobs:
  call-release-workflow:
    uses: gabrielzerio/devops/.github/workflows/Release.yml@main
    with:
      version: 'v1.0' # Você pode gerar essa versão dinamicamente
        # 4. Passe os 'secrets' necessários (eles devem existir no repositório 'frontend')
    secrets:
      API_TOKEN: "1234"
    
    # 1. Permissões necessárias para chamar outro workflow
    permissions:
      contents: read
