name: Trigger DevOps Release

on:
  push:
    branches:
      - release # Exemplo: dispara quando hรก um push na branch 'release'

jobs:
  call-release-workflow:
    permissions:
      contents: read
    uses: gabrielzerio/devops/.github/workflows/Release.yml@main
    with:
      version: 'v1.0'
    secrets:
      API_TOKEN: "1234"
